### ISSUE TITLE
Analytics 1.0.3 on Bolt 2.2.20 Class Google_Cache_Exception Bericht: Could not create storage directory

### ISSUE THREAD

**Issue by melcarthus** [bolt/GoogleAnalytics#11]
The following error occurred when I tried to setup the extension.

`Class Google_Cache_Exception
Bericht: Could not create storage directory: /tmp/Google_Client/13
Code 0`

addendum
I have installed this extension on the same server only on another website without any problems. I can't figure out why it should be a server permission error.

**Comment by SahAssar** [comment]
Closing since it's been a while since this was opened, if it's still a bug/relevant please reopen!
