### ISSUE TITLE
Compatibility with Bolt 3.0

### ISSUE THREAD

**Issue by willstorm** [bolt/GoogleAnalytics#14]
It's a great extension and I would apreciate to see this in Bolt 3.

**Comment by bobdenotter** [comment]
Test.. test..

**Comment by bobdenotter** [comment]
@willstorm Soon! See #12

**Comment by nbehier** [comment]
@bobdenotter I think this issue can now be closed.

**Comment by bobdenotter** [comment]
Yes, indeed. 👍
