### ISSUE TITLE
 ok, i got some time and i figured it out, now i get error after deployment ?

### ISSUE THREAD

**Issue by yanivyhc** [bolt/GoogleAnalytics#21]
Fatal error: Class 'Google_Service_Datastore_Resource_Projects' not found in /base/data/home/apps/projectName/12.396892754473494488/Google/Service/Datastore.php on line 56 ?

i see it fails in the constructor:

  public function __construct(Google_Client $client)
  {
    parent::__construct($client);
    $this->rootUrl = 'https://datastore.googleapis.com/';
    $this->servicePath = '';
    $this->version = 'v1';
    $this->serviceName = 'datastore';

    $this->projects = new Google_Service_Datastore_Resource_Projects(

is there any hint from your side ???
thanks

**Comment by bobdenotter** [comment]
I'm pretty sure this is not an Error related to the Bolt Google Analytics extension.
