### ISSUE TITLE
[RFC] Allow the possibility to change the cache location

### ISSUE THREAD

**Issue by SofaCitizen** [bolt/GoogleAnalytics#23]
I have deployed a site on a shared cloud host and run into an issue whereby the cache folder could not be created as it was already in use by someone else.

To fix this it would be handy if there was a configuration option to change this from the default (_sys_get_temp_dir() . '/Google_Client'_).

For example, after the "Create and configure a new client object." section of "GoogleAnalyticsHandler" (line 78), the following code can be added:
`$configLocation = sys_get_temp_dir() . '/Google_Client_' . $this->config->getUniversalDomainname();`
`$client->setClassConfig("Google_Cache_File", array('directory' => $configLocation));`

Alternatively, a better solution might be to add a new config variable which can be used?

**Comment by bobdenotter** [comment]
I'm pretty sure this is not an Error related to the Bolt Google Analytics extension.
