### ISSUE TITLE
Statistics not displayed - js error

### ISSUE THREAD

**Issue by opichon** [bolt/GoogleAnalytics#29]
The backend statistics page displays labels (eg "Visitors in the last 7 days, compared to the previous week") but not the graphs. 

Chrome dev tools reports this error: 
```
Uncaught TypeError: g.load is not a function
    at HTMLScriptElement.js.onload (google-analytics:568)
js.onload @ google-analytics:568
```

**Comment by opichon** [comment]
Same error with .pem file

**Comment by opichon** [comment]
Oops. Ghostery was blocking google analytics.

**Comment by bobdenotter** [comment]
@opichon Closing this issue then. Feel free to re-open, if needed. :-)
