### ISSUE TITLE
Make "displayfeatures" setting available

### ISSUE THREAD

**Issue by DanielKulbe** [bolt/GoogleAnalytics#3]
Google Analytics "universal" provides the possibility to track demographic information. For this you need to extend the script after you created the web property.

I'd like to have the possibility to add this information right in the config.yml file with some minor changes in the Extension.php.

**Comment by SahAssar** [comment]
Closing as it's been a while and I'm guessing that we'd need a new approach to this anyway to cover all the bases, for example we are looking at the e-commerce tracking which also requires some extension of the script.
