### ISSUE TITLE
Causes "502 Bad Gateway" error on Bolt 3.3.2

### ISSUE THREAD

**Issue by BlakeBeus** [bolt/GoogleAnalytics#33]
There are several symptoms to this issue.

### Upgrading to Bolt 3.3.2 from 3.2.x via composer
After running `composer update` when I run `php app/nut cache:clear` I get a `Segmentation fault (core dumped)` error in the terminal.  This problem persists with all app/nut commands from this point on.

### Installing the extension from the admin panel
When I install this extension from the admin panel I get a `Unexpected token < in JSON at position 0` and then the site isn't usable anymore.  If the page is refreshed I am presented `502 Bad Gateway` error.

The error log on the server shows the below error for every request to the webpage:

```
2017/08/26 15:54:57 [error] 1022#1022: *180 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.69.1, server: www.example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "www.example.com"
```

### Environment
Ubuntu 16.04 VPS, PHP-FPM 7.1, Nginx, MariaDB

I can reproduce this error on the fly, so I can provide additional details if needed.

**Comment by GawainLynch** [comment]
Yeah, I was able to reproduce this today and coded up #32 to address this and a few other things. It needs some testing from someone who has slept … which isn't me … yet :wink: 

Expect a new release soon that will address this and have you up and working with both this extension and Bolt 3.3.

**Comment by Jogai** [comment]
Me too on 3.3.3

> JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by GawainLynch** [comment]
Fix is coming … just reviewers are time poor this week :smile:
