### ISSUE TITLE
GAPI: Failed to authenticate user

### ISSUE THREAD

**Issue by jamiroconca** [bolt/GoogleAnalytics#7]
suddenly the widget in the dashboard has become unavailable, sytem log says
"GAPI: Failed to authenticate user. Error: "https://developers.google.com/accounts/docs/AuthForInstalledApps ""

the google's page says
"Important: ClientLogin has been officially deprecated since April 20, 2012 and is now no longer available. Requests to ClientLogin will fail with a HTTP 404 response. We encourage you to migrate to OAuth 2.0 as soon as possible."

**Comment by jeffpfoster** [comment]
The master branch has the OAuth 2.0 code in it.  You'll have to enable the non stable extensions and then install the dev-master branch of the extension.  Then you can follow the steps in the pull request I created to setup the new OAuth settings.

**Comment by SahAssar** [comment]
Closing since this issue is long outdated and no longer relevant to the code currently used.
